# Generated by Django 4.1.1 on 2022-09-27 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brewery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=150)),
                ('description', models.TextField(max_length=300)),
                ('toptap', models.CharField(max_length=200)),
                ('established', models.IntegerField()),
                ('image', models.ImageField(default='', upload_to='main_app/static/uploads')),
            ],
        ),
    ]
