# Generated by Django 4.1.1 on 2022-09-28 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialbrews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=300)),
                ('date', models.DateField()),
                ('variety', models.CharField(choices=[('DIPA', 'Double Indian Pale Ale'), ('IPA', 'Indian Pale Ale'), ('PA', 'Pale Ale'), ('L', 'Lager'), ('STO', 'Stout'), ('WHA', 'Wheat Ale'), ('SIP', 'Session Indian Pale Ale'), ('TIP', 'Triple Indian Pale Ale'), ('SOUR', 'Sour ale')], default='D', max_length=4)),
                ('brewery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.brewery')),
            ],
        ),
    ]
