# Generated by Django 4.1.1 on 2022-09-29 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_specialbrews'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Specialbrews',
            new_name='Specialbrew',
        ),
    ]
