# Generated by Django 4.1.1 on 2022-09-30 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_rename_specialbrews_specialbrew'),
    ]

    operations = [
        migrations.CreateModel(
            name='Corebrew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=300)),
                ('variety', models.CharField(choices=[('DIPA', 'Double Indian Pale Ale'), ('IPA', 'Indian Pale Ale'), ('PA', 'Pale Ale'), ('L', 'Lager'), ('STO', 'Stout'), ('WHA', 'Wheat Ale'), ('SIP', 'Session Indian Pale Ale'), ('TIP', 'Triple Indian Pale Ale'), ('SOUR', 'Sour ale')], default='D', max_length=4)),
                ('brewery', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterModelOptions(
            name='specialbrew',
            options={'ordering': ['date']},
        ),
    ]
