# Generated by Django 4.1.1 on 2022-09-30 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_corebrew_alter_specialbrew_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='corebrew',
            old_name='brewery',
            new_name='corebrewery',
        ),
    ]
