# Generated by Django 4.1.1 on 2022-09-30 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_rename_brewery_corebrew_corebrewery'),
    ]

    operations = [
        migrations.AddField(
            model_name='brewery',
            name='corebrews',
            field=models.ManyToManyField(to='main_app.corebrew'),
        ),
    ]
